from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='home'),
    path('bookings/', views.carePage, name='care'),
    # path('careBooked/', views.careBookedPage, name='careBooked'),
    path('book1/<int:hospital_id>/', views.book1Page, name='book1'),
    path('book2/', views.book2Page, name='book2'),
    path('book3/', views.book3Page, name='book3'),
    path('book4/', views.book4Page, name='book4'),
    path('book5/', views.book5Page, name='book5'),
    path('login/', views.loginPage, name='login'),
    # path('modal-login/', views.modalLogin, name='modal_login'),
    path('signup/', views.registerPage, name='register'),
    path('signup1/', views.register1Page, name='register1'),
    path('verifyUpdateEmail/', views.verifyUpdateEmail, name='verifyUpdateEmail'),
    path('signup2/', views.register2Page, name='register2'),
    path('logout/', views.logoutPage, name='logout'),
    path('mydata/', views.myData, name='mydata'),
    path('account/', views.accountPage, name='account'),
    path('personal/', views.personalPage, name='personal'),
    path('medicalInfo/', views.medicalInfoPage, name='medicalInfo'),
    path('setting/', views.setting, name='setting'),
    path('passwordsecurityPage/', views.passwordsecurityPage, name='passwordsecurityPage'),
    path('changePassword/', views.changePassword, name='changePassword'),
    path('update_fullname/', views.update_fullname, name='update_fullname'),
    path('update_gender/', views.update_gender, name='update_gender'),
    path('update_dob/', views.update_dob, name='update_dob'),
    path('update_email/', views.update_email, name='update_email'),
    path('update_nationality/', views.update_nationality, name='update_nationality'),
    path('update_language/', views.update_language, name='update_language'),
    path('update_height/', views.update_height, name='update_height'),
    path('update_weight/', views.update_weight, name='update_weight'),
    path('update_insurance/', views.update_insurance, name='update_insurance'),
    path('update_phone/', views.update_phone, name='update_phone'),
    path('change_language/', views.change_language, name='change_language'),
    path('findHospital/', views.findHospital, name='findHospital'),
    path('hospitalInfo/<str:pk>/', views.hospitalInfo, name='hospitalInfo'),
    path('bookedHospitalDetail/<str:pk>/', views.bookedHospitalDetail, name='bookedHospitalDetail'),
    # path('diagnose/', views.diagnose, name='diagnose_start'),
    # path('diagnose/<int:question_id>/', views.diagnose, name='diagnose'),
    path('conclusion-detail/<int:id_conclusion>/', views.conclusion_detail, name='conclusion-detail'),
    path('history/', views.history, name='history'),
    path('insurance/', views.insurance, name='insurance'),
    path('saved/', views.saved, name='saved'),
    path('add_to_favourites/<int:hospital_id>/', views.add_to_favourites, name='add_to_favourites'),
    path('remove_from_favourites/<int:hospital_id>/', views.remove_from_favourites, name='remove_from_favourites'),
    path('filter/', views.filter, name='filter'),
    path('reset_filter/', views.reset_filter, name='reset_filter'),
    path('verify_account/', views.verify_account, name='verify_account'),
    path('verify_account_register/', views.verify_account_register, name='verify_account_register'),
    path('resend_verification_code/', views.resend_verification_code, name='resend_verification_code'),
    path('resend_verification_code_register/', views.resend_verification_code_register, name='resend_verification_code_register'),
    path('list_booked_hospital/', views.list_booked_hospital, name='list_booked_hospital'),
    path('approve_booked_hospital/<int:booked_id>/', views.approve_booked_hospital, name='approve_booked_hospital'),
    path('reject_booked_hospital/<int:booked_id>/', views.reject_booked_hospital, name='reject_booked_hospital'),
    path('cancel_booked_hospital/<int:booked_id>/', views.cancel_booked_hospital, name='cancel_booked_hospital'),
    path('delete_booked_hospital/<int:booked_id>/', views.delete_booked_hospital, name='delete_booked_hospital'),
    path('edit_booked_hospital/<int:booked_id>/', views.edit_booked_hospital, name='edit_booked_hospital'),

    path('hospitals/', views.hospital_list, name='hospital_list'),
    path('hospitals/create/', views.hospital_create, name='hospital_create'),
    path('hospitals/update/<int:id>/', views.hospital_update, name='hospital_update'),
    path('hospitals/delete/<int:id>/', views.hospital_delete, name='hospital_delete'),

    path('workinghours/', views.working_hours_list, name='working_hours_list'),
    path('workinghours/create/', views.working_hours_create, name='working_hours_create'),
    path('workinghours/update/<int:id>/', views.working_hours_update, name='working_hours_update'),
    path('workinghours/delete/<int:id>/', views.working_hours_delete, name='working_hours_delete'),

    path('hospitalimages/', views.hospital_image_list, name='hospital_image_list'),
    path('hospitalimages/create/', views.hospital_image_create, name='hospital_image_create'),
    path('hospitalimages/update/<int:id>/', views.hospital_image_update, name='hospital_image_update'),
    path('hospitalimages/delete/<int:id>/', views.hospital_image_delete, name='hospital_image_delete'),

    path('distanceinfo/', views.distance_info_list, name='distance_info_list'),
    path('distanceinfo/create/', views.distance_info_create, name='distance_info_create'),
    path('distanceinfo/update/<int:id>/', views.distance_info_update, name='distance_info_update'),
    path('distanceinfo/delete/<int:id>/', views.distance_info_delete, name='distance_info_delete'),

    path('save_distance/', views.save_distance_data, name='save_distance_data'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
