# Generated by Django 4.2.7 on 2024-07-30 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_hospital_latitude_hospital_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='longitude',
        ),
    ]
