# Generated by Django 4.2.7 on 2024-07-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_patient_latitude_patient_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='longitude',
        ),
        migrations.AddField(
            model_name='hospital',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
