# Generated by Django 4.2.7 on 2024-08-07 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_patient_latitude_remove_patient_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalbooking',
            name='phone',
            field=models.CharField(max_length=30),
        ),
    ]
