# Generated by Django 4.2.7 on 2024-08-07 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
