# Generated by Django 4.2.7 on 2024-08-20 03:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalbooking',
            name='first_date_from_reserved',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hospitalbooking',
            name='first_date_reserved',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hospitalbooking',
            name='first_date_to_reserved',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hospitalbooking',
            name='second_date_from_reserved',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitalbooking',
            name='second_date_reserved',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitalbooking',
            name='second_date_to_reserved',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
