# Generated by Django 4.2.7 on 2024-08-20 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_hospitalbooking_first_date_from_reserved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalbooking',
            name='first_date_from_reserved',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalbooking',
            name='first_date_reserved',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalbooking',
            name='first_date_to_reserved',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
