# Generated by Django 4.2.7 on 2024-09-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_hospitalbooking_first_date_from_reserved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalbooking',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hospitalbooking',
            name='token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
