# Generated by Django 4.2.7 on 2024-09-10 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_hospitalbooking_token_hospitalbooking_token_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalbooking',
            name='token',
        ),
        migrations.RemoveField(
            model_name='hospitalbooking',
            name='token_expiry',
        ),
    ]
