# Generated by Django 4.2.7 on 2024-09-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_hospitalbooking_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalbooking',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
