# Generated by Django 4.2.7 on 2024-09-10 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_hospitalbooking_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalbooking',
            name='token',
        ),
    ]
