# Generated by Django 4.2.7 on 2024-10-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_hospitalbooking_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='placeId',
            field=models.TextField(blank=True, null=True),
        ),
    ]
