# Generated by Django 4.2.7 on 2024-10-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_hospital_placeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='api_data_stale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hospital',
            name='last_api_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
