# Generated by Django 4.2.7 on 2024-10-25 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_hospital_api_data_stale_hospital_last_api_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('review_time', models.DateTimeField()),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='home.hospital')),
            ],
        ),
    ]
