# Generated by Django 4.2.7 on 2024-10-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='user_ratings_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
