# Generated by Django 4.2.7 on 2024-10-25 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_hospital_user_ratings_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='api_data_stale',
        ),
    ]
