# Generated by Django 4.2.7 on 2024-10-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_hospital_api_data_stale'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='profile_photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
