# Generated by Django 4.2.7 on 2024-10-28 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_review_profile_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_time',
            field=models.CharField(max_length=50),
        ),
    ]
