# Generated by Django 4.2.7 on 2024-10-28 03:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_review_review_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
