# Generated by Django 4.2.7 on 2024-11-06 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_patient_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslatedReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ja', 'Japanese')], max_length=10)),
                ('translated_text', models.TextField()),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.review')),
            ],
        ),
    ]
