# Generated by Django 4.2.7 on 2024-11-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_translatedreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalbooking',
            name='utm_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
