# Generated by Django 4.2.7 on 2024-11-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_hospitalbooking_utm_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
