# Generated by Django 4.2.7 on 2024-11-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_review_author_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalimage',
            name='original_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
