# Generated by Django 4.2.7 on 2024-11-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_hospitalimage_original_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalimage',
            name='unique_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
